config/routes.rb
WeeklySchedule::Application.routes.draw do
  mount API => '/'

  resources :dashboards
  resources :experiences
  resources :skills
  resources :reports, only: [:index]
  resources :doc_auths
  resources :week_hours
  resources :raw_items, only: [:index, :destroy]
  resources :projects
  resources :leave_requests

  resources :schedules do
    collection do
      get :load_from_google
      get :batch_create
      get :check_sending_status
      get :check_importing_status
      get :weekly_send_mails
    end
  end

  resources :users do
    member do
      get :skills
    end
  end

  resources :groups

  resources :settings, :only => :index

  match 'setup', :to => 'settings#setup', :via => [:get, :post]
  get 'switch_mode', :to => 'settings#mode'
  get 'switch_user', :to => 'settings#user'

  namespace :settings do
    get 'mail_templates/edit', to: 'mail_templates#edit',   as: :edit_mail_templates
    put 'mail_templates',      to: 'mail_templates#update', as: :update_mail_templates

    get 'harvest/edit',          to: 'harvest#edit',          as: :edit_harvest
    put 'harvest',               to: 'harvest#update',        as: :update_harvest
    get 'harvest/refresh_token', to: 'harvest#refresh_token', as: :refresh_harvest_token

    get 'confluence/edit',          to: 'confluence#edit',          as: :edit_confluence
    put 'confluence',               to: 'confluence#update',        as: :update_confluence

    get 'google/edit',          to: 'google#edit',          as: :edit_google
    put 'google',               to: 'google#update',        as: :update_google

    get 'app_settings/edit',          to: 'app_settings#edit',          as: :edit_app_settings
    put 'app_settings',               to: 'app_settings#update',        as: :update_app_settings
  end

  put 'settings/:auto_mail', :to => 'settings#update', :as => :setting
  put 'mail_settings', :to => 'settings#update', :as => :mail_settings
  get 'settings/:auto_mail', :to => 'settings#update', :as => :setting_mails

  root :to => 'dashboards#index'

  match '/auth/harvest/callback' => 'settings/harvest#refresh_token'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

end

app/models/group.rb
class Group < ActiveRecord::Base
  serialize :cc

  attr_accessible :name, :display, :cc, :from, :message, :ending_content

  default_scope order('display DESC')

  validates :name, :presence => true
  validates :name, :uniqueness => true
  validates :from, :presence => true

  has_many :users, :dependent => :nullify
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_users_for_select
  load_and_authorize_resource
  respond_to :html

  def index
    @groups = Group.all
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:notice] = 'Group was successfully created'
    end

    respond_with @group
  end

  def update
    if @group.update_attributes(params[:group])
      flash[:notice] = 'Group was successfully updated'
    end
    redirect_to groups_path
  end

  def destroy
    @group.destroy
    respond_with @group
  end

  protected

    def load_users_for_select
      @users_for_select = User.order("name ASC").collect{|c| [c.name, c.email] if not c.email.blank?}.uniq.compact
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Group</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
        <label class="checkbox">
          <%= f.check_box :display %> Active (display in list and send email)
        </label>
      </div>
    </div>

    <legend>Custom Group Email</legend>
    <div class="control-group">
      <%= label_tag 'From', nil, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :from, options_for_select(@users_for_select, @group.from), :prompt => 'Select From', :style => "width:385px;", :class => 'text_field chzn-select' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag 'CC', nil, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :cc, options_for_select(@users_for_select, @group.cc), {}, :multiple => true, :prompt => 'Select Some People', :style => "width:385px;", :class => 'text_field chzn-select' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag "Message", nil, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => 'text_area', :style => "width:385px;height:200px;" %>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag "Ending Content", nil, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :ending_content, :class => 'text_area', :style => "width:385px;height:200px;" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', groups_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/groups/edit.html.erb
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Group Name</th>
      <th>Display in list</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <% @group = group %>
      <tr>
        <td><%= @group.name %></td>
        <td><%= @group.display? %></td>
        <td>
          <% if can? :show, group %>
          <%= link_to 'Show', group_path(group), :class => 'btn btn-mini' %>
          <% end %>

          <% if can? :update, group %>
          <%= link_to 'Edit', edit_group_path(group), :class => 'btn btn-mini' %>
          <% end %>

          <% if can? :destroy, group %>
          <%= link_to 'Destroy', group_path(group), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Group %>
<%= link_to 'New', new_group_path, :class => 'btn btn-primary' %>
<% end %>

<br/ ><br />

app/views/groups/new.html.erb
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<h1>Group</h1>
<br />
<p>
  <h4>Name</h4>
  <%= @group.name %>
</p>
<p>
  <h4>CC</h4>
  <%= @group.cc %>
</p>
<p>
  <h4>From</h4>
  <%= @group.from %>
</p>
<p>
  <h4>Message</h4>
  <%= @group.message %>
</p>
<p>
  <h4>Ending Content</h4>
  <%= @group.ending_content %>
</p>

<div class="form-actions">
  <% if can? :index, Group %>
  <%= link_to 'Back', groups_path, :class => 'btn'  %>
  <% end %>

  <% if can? :update, @group %>
  <%= link_to 'Edit', edit_group_path(@group), :class => 'btn' %>
  <% end %>

  <% if can? :destroy, @group %>
  <%= link_to 'Delete', group_path(@group), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  <% end %>
</div>