config/routes.rb
WeeklySchedule::Application.routes.draw do
  mount API => '/'

  resources :dashboards
  resources :experiences
  resources :skills
  resources :reports, only: [:index]
  resources :doc_auths
  resources :week_hours
  resources :raw_items, only: [:index, :destroy]
  resources :projects
  resources :leave_requests

  resources :schedules do
    collection do
      get :load_from_google
      get :batch_create
      get :check_sending_status
      get :check_importing_status
      get :weekly_send_mails
    end
  end

  resources :users do
    member do
      get :skills
    end
  end

  resources :groups

  resources :settings, :only => :index

  match 'setup', :to => 'settings#setup', :via => [:get, :post]
  get 'switch_mode', :to => 'settings#mode'
  get 'switch_user', :to => 'settings#user'

  namespace :settings do
    get 'mail_templates/edit', to: 'mail_templates#edit',   as: :edit_mail_templates
    put 'mail_templates',      to: 'mail_templates#update', as: :update_mail_templates

    get 'harvest/edit',          to: 'harvest#edit',          as: :edit_harvest
    put 'harvest',               to: 'harvest#update',        as: :update_harvest
    get 'harvest/refresh_token', to: 'harvest#refresh_token', as: :refresh_harvest_token

    get 'confluence/edit',          to: 'confluence#edit',          as: :edit_confluence
    put 'confluence',               to: 'confluence#update',        as: :update_confluence

    get 'google/edit',          to: 'google#edit',          as: :edit_google
    put 'google',               to: 'google#update',        as: :update_google

    get 'app_settings/edit',          to: 'app_settings#edit',          as: :edit_app_settings
    put 'app_settings',               to: 'app_settings#update',        as: :update_app_settings
  end

  put 'settings/:auto_mail', :to => 'settings#update', :as => :setting
  put 'mail_settings', :to => 'settings#update', :as => :mail_settings
  get 'settings/:auto_mail', :to => 'settings#update', :as => :setting_mails

  root :to => 'dashboards#index'

  match '/auth/harvest/callback' => 'settings/harvest#refresh_token'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

end

app/models/doc_auth.rb
class DocAuth < ActiveRecord::Base
  attr_accessible :username, :password, :key, :current

  validates :username, :presence => true
  validates :password, :presence => true
  validates :key, :presence => true


  def self.current_doc
    self.where(:current => true).first
  end

  def set_as_current
    DocAuth.all.each do |d|
      if d == self
        self.update_attributes(:current => true)
      else
        d.update_attributes(:current => false)
      end
    end
  end

  def value_of(key)
    self.try(key) || DocAuth.first.try(key)
  end
end

app/controllers/doc_auths_controller.rb
class DocAuthsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  respond_to :html

  def index
    @doc_auths = DocAuth.all
  end

  def create
    @doc_auth = DocAuth.new params[:doc_auth]
    if @doc_auth.save
      flash[:notice] = 'Google spreadsheet was successfully added'
    end
    respond_with @doc_auth, location: doc_auths_path
  end

  def update
    if @doc_auth.update_attributes(params[:doc_auth])
      if @doc_auth.current?
        @doc_auth.set_as_current
      end
    end
    respond_with @doc_auth, location: doc_auths_path
  end

  def destroy
    @doc_auth.destroy
    respond_to @doc_auth
  end
end

app/helpers/doc_auths_helper.rb
module DocAuthsHelper
end

app/views/doc_auths/_form.html.erb
<%= form_for @doc_auth, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Doc Auth</legend>

    <div class="control-group">
      <%= f.label :key, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :key, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :current, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :current %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', doc_auths_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/doc_auths/edit.html.erb
<%= render :partial => 'form' %>

app/views/doc_auths/index.html.erb
<h1>Doc Auths</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Key</th>
      <th>Current?</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @doc_auths.each do |doc_auth| %>
      <tr>
        <td><%= doc_auth.id %></td>
        <td><%= link_to doc_auth.key, doc_auth_path(doc_auth) %></td>
        <th><%= doc_auth.current? %></th>
        <td><%= doc_auth.created_at %></td>
        <td>
          <% if can? :update, doc_auth %>
          <%= link_to 'Edit', edit_doc_auth_path(doc_auth), :class => 'btn btn-mini' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, DocAuth %>
<%= link_to 'New Google Spreadsheet', new_doc_auth_path, :class => 'btn btn-primary' %>
<% end %>

app/views/doc_auths/new.html.erb
<%= render :partial => 'form' %>

app/views/doc_auths/show.html.erb
<h1>Doc Auth</h1>

<p>
  <b>Key</b><br>
  <%= @doc_auth.key %>
</p>

<p>
  <b>Username</b><br>
  <%= @doc_auth.username %>
</p>

<div class="form-actions">
  <%= link_to 'Back', doc_auths_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_doc_auth_path(@doc_auth), :class => 'btn' %>
  <%= link_to 'Delete', doc_auth_path(@doc_auth), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>