config/routes.rb
WeeklySchedule::Application.routes.draw do
  mount API => '/'

  resources :dashboards
  resources :experiences
  resources :skills
  resources :reports, only: [:index]
  resources :doc_auths
  resources :week_hours
  resources :raw_items, only: [:index, :destroy]
  resources :projects
  resources :leave_requests

  resources :schedules do
    collection do
      get :load_from_google
      get :batch_create
      get :check_sending_status
      get :check_importing_status
      get :weekly_send_mails
    end
  end

  resources :users do
    member do
      get :skills
    end
  end

  resources :groups

  resources :settings, :only => :index

  match 'setup', :to => 'settings#setup', :via => [:get, :post]
  get 'switch_mode', :to => 'settings#mode'
  get 'switch_user', :to => 'settings#user'

  namespace :settings do
    get 'mail_templates/edit', to: 'mail_templates#edit',   as: :edit_mail_templates
    put 'mail_templates',      to: 'mail_templates#update', as: :update_mail_templates

    get 'harvest/edit',          to: 'harvest#edit',          as: :edit_harvest
    put 'harvest',               to: 'harvest#update',        as: :update_harvest
    get 'harvest/refresh_token', to: 'harvest#refresh_token', as: :refresh_harvest_token

    get 'confluence/edit',          to: 'confluence#edit',          as: :edit_confluence
    put 'confluence',               to: 'confluence#update',        as: :update_confluence

    get 'google/edit',          to: 'google#edit',          as: :edit_google
    put 'google',               to: 'google#update',        as: :update_google

    get 'app_settings/edit',          to: 'app_settings#edit',          as: :edit_app_settings
    put 'app_settings',               to: 'app_settings#update',        as: :update_app_settings
  end

  put 'settings/:auto_mail', :to => 'settings#update', :as => :setting
  put 'mail_settings', :to => 'settings#update', :as => :mail_settings
  get 'settings/:auto_mail', :to => 'settings#update', :as => :setting_mails

  root :to => 'dashboards#index'

  match '/auth/harvest/callback' => 'settings/harvest#refresh_token'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

end

app/controllers/settings/app_settings_controller.rb
class Settings::AppSettingsController < Settings::Base
  def update
    if params[:app_settings].blank?
      redirect_to settings_edit_app_settings_path,
        alert: 'Application settings are required'
    else
      AppSettings.google_analytics_tracker = params[:app_settings][:google_analytics_tracker]
      AppSettings.dashboard_api_key = params[:app_settings][:dashboard_api_key]
      AppSettings.feedback_url = params[:app_settings][:feedback_url]
      redirect_to settings_path,
        notice: 'Application Settings Updated'
    end
  end
end

app/controllers/settings/base.rb
class Settings::Base < ApplicationController
  before_filter :authenticate_user!, :require_permission

  def edit
  end

  private

  def require_permission
    authorize!(:update, AppSettings)
  end

end

app/controllers/settings/confluence_controller.rb
class Settings::ConfluenceController < Settings::Base
  def edit
    @settings = AppSettings.confluence.try(:[], Rails.env.to_sym) || {}
  end

  def update
    if params[:confluence].blank?
      redirect_to settings_edit_confluence_path,
        alert: 'Confluence settings are required'
    else
      AppSettings.confluence = {Rails.env.to_sym => params[:confluence].symbolize_keys}
      ::Configuration::Confluence.connect()
      redirect_to settings_path,
        notice: 'Confluence Settings Updated'
    end
  end
end

app/controllers/settings/google_controller.rb
class Settings::GoogleController < Settings::Base
  def update
    if params[:app_settings][:google_client_id].blank? || params[:app_settings][:google_client_secret].blank?
      redirect_to settings_edit_google_path,
        alert: 'Google OAuth settings are required'
    else
      AppSettings.google_client_id = params[:app_settings][:google_client_id]
      AppSettings.google_client_secret = params[:app_settings][:google_client_secret]
      User.where(role: 'SuperAdmin').map { |u| u.update_attribute(:logged_in, nil) }
      redirect_to settings_path,
        notice: 'Google OAuth Settings Updated'
    end
  end
end

app/controllers/settings/harvest_controller.rb
class Settings::HarvestController < Settings::Base
  def update
    if params[:identifier].blank? || params[:secret].blank?
      redirect_to settings_edit_harvest_path,
        alert: 'Identifier and secret are required'
    else
      AppSettings.harvest_identifier = params[:identifier]
      AppSettings.harvest_secret     = params[:secret]
      redirect_to settings_edit_harvest_path,
        notice: 'Harvest Settings Updated'
    end
  end

  def refresh_token
    expires_at = Time.at(env['omniauth.auth']['credentials']['expires_at'])
    current_user.update_attributes({
      harvest_token: env['omniauth.auth']['credentials']['token'],
      harvest_refresh_token: env['omniauth.auth']['credentials']['refresh_token'],
      expires_at: (expires_at + 30.days),
      refresh_at: expires_at
    })
    redirect_to :edit_harvest_path
  end
end

app/controllers/settings/mail_templates_controller.rb
class Settings::MailTemplatesController < Settings::Base
  before_filter :authenticate_user!, :require_permission

  def edit
    @users_for_select = User.order("name ASC").collect{ |c|
      [c.name, c.email] if not c.email.blank?
    }.uniq.compact
  end

  def update
    if params[:auto_mail].present?
      AppSettings.auto_mail = params[:auto_mail]
      message = "You have set the application as #{AppSettings.auto_mail == 'on' ? 'AUTOMATICALLY SEND MAIL' : 'Manually SEND Mail' }!"
    else
      puts params
      params[:settings].each_pair do |setting, value|
        AppSettings.send(setting.to_s+"=", value)
      end
      message = "All mail settings are saved successfully!"
    end

    redirect_to :back, :notice => message
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!, except: [:setup, :mode]
  before_filter :setup_completed?, only: :setup

  def setup
    @config = DashboardConfig.new(params[:config_form])

    if request.post? && @config.save
      AppSettings.mode = 'normal'
      redirect_to root_path, alert: 'Setup completed!'
    end
  end

  def mode
    if params[:to] == 'demo' && Import.last.nil? && AppSettings.mode.nil?
      AppSettings.mode = 'demo'

      AppSettings.confluence = {
        Rails.env.to_sym => {
          url: "https://intridea.atlassian.net/wiki/rpc/soap-axis/confluenceservice-v2?wsdl",
          user: "public.user",
          password: "publicuser123",
          space: "HOUSTON",
          faq_parent: "41975830",
          faq_link: "https://intridea.atlassian.net/wiki/display/HOUSTON/Houston+Demo+Home" }
      }
      ::Configuration::Confluence.connect()

      DemoImporter.new.import
      Schedule.reload_schedules
      session[:user_id] = Schedule.all.map(&:user_id).sample

      redirect_to root_path
    else
      redirect_to root_path, alert: 'Failed to switch to demo mode.'
    end
  end

  def user
    if AppSettings.mode == 'demo' && u = User.find_by_name(params[:name])
      session[:user_id] = u.id
    end

    redirect_to root_path
  end

  def index
  end

  def update_harvest
    expires_at = Time.at(env['omniauth.auth']['credentials']['expires_at'])
    current_user.update_attributes({
      harvest_token: env['omniauth.auth']['credentials']['token'],
      harvest_refresh_token: env['omniauth.auth']['credentials']['refresh_token'],
      expires_at: (expires_at + 30.days),
      refresh_at: expires_at
    })
    redirect_to '/settings/harvest'
  end

  private

  def setup_completed?
    if ::Configuration::GoogleOmniauth.configured? && User.configured?
      redirect_to root_url, alert: "Access denied"
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<ul>
  <li><%= link_to('Mail Templates', settings_edit_mail_templates_path) %></li>
  <li><%= link_to('Harvest', settings_edit_harvest_path) %></li>
  <li><%= link_to('Confluence', settings_edit_confluence_path) %></li>
  <li><%= link_to('Google OAuth', settings_edit_google_path) %></li>
  <li><%= link_to('Application Settings', settings_edit_app_settings_path) %></li>
</ul>

app/views/settings/setup.html.erb
<% if @config.errors.any? -%>
<div id="error_explanation">
   <h2><%= pluralize(@config.errors.count, "error") %> prohibited this configuration from being saved:</h2>
   <ul>
     <% @config.errors.full_messages.each do |msg| %>
       <li> * <%= msg %></li>
     <% end %>
   </ul>
</div>
<% end -%>

<div class='row'>
  <div class='col-md-4'>
    <h2>Option 1: Fill in basic info and get ready to log in users!</h2>
    <%= form_for @config, :url => setup_path, :as => 'config_form', :html => { :class => 'form-horizontal setup' } do |f| %>
      <div class="control-group">
        <%= f.label "Google Oauth Client ID", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :client_id, :class => 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label "Google Oauth Client Secret", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :client_secret, :class => 'text_field' %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label "Your Google Email", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :email, :class => 'text_field' %>
          <p class="hint">(for SuperAdmin powers)</p>
        </div>
      </div>

      <br/>

      <div class="form-actions">
        <%= f.submit "Let's do this", :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <div class='col-md-2'> </div>

  <% if AppSettings.mode.nil? %>
  <div class='col-md-4'>
    <h2>Option 2: Click below to enter demo mode. The fastest way to have fun.</h2>
    <%= link_to 'Switch to Demo Mode', switch_mode_path(to: 'demo'), :class => 'btn btn-primary' %>
  </div>
  <% end %>
</div>