config/routes.rb
WeeklySchedule::Application.routes.draw do
  mount API => '/'

  resources :dashboards
  resources :experiences
  resources :skills
  resources :reports, only: [:index]
  resources :doc_auths
  resources :week_hours
  resources :raw_items, only: [:index, :destroy]
  resources :projects
  resources :leave_requests

  resources :schedules do
    collection do
      get :load_from_google
      get :batch_create
      get :check_sending_status
      get :check_importing_status
      get :weekly_send_mails
    end
  end

  resources :users do
    member do
      get :skills
    end
  end

  resources :groups

  resources :settings, :only => :index

  match 'setup', :to => 'settings#setup', :via => [:get, :post]
  get 'switch_mode', :to => 'settings#mode'
  get 'switch_user', :to => 'settings#user'

  namespace :settings do
    get 'mail_templates/edit', to: 'mail_templates#edit',   as: :edit_mail_templates
    put 'mail_templates',      to: 'mail_templates#update', as: :update_mail_templates

    get 'harvest/edit',          to: 'harvest#edit',          as: :edit_harvest
    put 'harvest',               to: 'harvest#update',        as: :update_harvest
    get 'harvest/refresh_token', to: 'harvest#refresh_token', as: :refresh_harvest_token

    get 'confluence/edit',          to: 'confluence#edit',          as: :edit_confluence
    put 'confluence',               to: 'confluence#update',        as: :update_confluence

    get 'google/edit',          to: 'google#edit',          as: :edit_google
    put 'google',               to: 'google#update',        as: :update_google

    get 'app_settings/edit',          to: 'app_settings#edit',          as: :edit_app_settings
    put 'app_settings',               to: 'app_settings#update',        as: :update_app_settings
  end

  put 'settings/:auto_mail', :to => 'settings#update', :as => :setting
  put 'mail_settings', :to => 'settings#update', :as => :mail_settings
  get 'settings/:auto_mail', :to => 'settings#update', :as => :setting_mails

  root :to => 'dashboards#index'

  match '/auth/harvest/callback' => 'settings/harvest#refresh_token'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  attr_accessible :level, :notes, :skill_id, :user_id, :years

  belongs_to :user
  belongs_to :skill
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_filter :authenticate_user!
  load_resource
  respond_to :html

  def index
    @experiences = Experience.all
  end

  def create
    @experience = Experience.new params[:experience]
    if @experience.save
      flash[:notice] = 'Experice was successfully created'
    end

    respond_with @experience
  end

  def update
    if @experience.update_attributes params[:experience]
      flash[:notice] = 'Experice was successfully updated'
    end

    respond_with @experience
  end

  def destroy
    @experience.destroy
    respond_with @experience
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :skill_id %><br />
    <%= f.number_field :skill_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :years %><br />
    <%= f.text_field :years %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<h1>Listing experiences</h1>

<table>
  <tr>
    <th>Level</th>
    <th>Notes</th>
    <th>Skill</th>
    <th>User</th>
    <th>Years</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experiences.each do |experience| %>
  <tr>
    <td><%= experience.level %></td>
    <td><%= experience.notes %></td>
    <td><%= experience.skill_id %></td>
    <td><%= experience.user_id %></td>
    <td><%= experience.years %></td>
    <td><%= link_to 'Show', experience %></td>
    <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
    <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @experience.level %>
</p>

<p>
  <b>Notes:</b>
  <%= @experience.notes %>
</p>

<p>
  <b>Skill:</b>
  <%= @experience.skill_id %>
</p>

<p>
  <b>User:</b>
  <%= @experience.user_id %>
</p>

<p>
  <b>Years:</b>
  <%= @experience.years %>
</p>


<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>